### ISSUE TITLE
Closed status not updating correctly

### ISSUE THREAD

**Issue by getridofwires** [drewgould/homebridge-garageio#1]
First, thank you for creating this. I installed it on my R Pi Homebridge, and it opens/closes the doors correctly. But the Open/Closed status does not update correctly on the Home app. It shows the "Opening" and "Closing" animation with the Wait circle correctly, but when the Closing process finishes, it leaves the Home app icon in the Open state. It seems to work OK for the Open status, which is odd. I have checked my door sensors and they are OK, and work correctly with the Garageio app. If I'm doing something wrong, please let me know. Again thanks for writing this.

**Comment by jianyu-li** [comment]
@getridofwires are you still experiencing these issues? I’m considering using this plugin. thanks

**Comment by yangyman** [comment]
I’m having a similar issue, any updates?
