### ISSUE TITLE
Garageio App Deprecated

### ISSUE THREAD

**Issue by JedWare** [drewgould/homebridge-garageio#3]
Heard back from company. Apparently there is a new app and you are suppose to migrate. There doesn't appear to be any homebridge plug-ins that support it though.

"Garageio is being phased out, however you can switch over to Beam. Please use the link for additional information.
https://help.beamlabs.io/article/52-garageio-beam-home-transition "

Any chance on updating this plugin?

**Comment by drewgould** [comment]
I no longer have the garageio system but I gave it to my dad. We live in different states but I'll take a look at the Beam app as visually it looks exactly the same as Garageio. If it's a matter of just changing a domain and the APIs are the same I can push an update. If they significantly changed the way the APIs work I more than likely won't update this.

**Comment by drewgould** [comment]
I had emailed Garageio support because the SSL cert for garageio.com expired, and I just received this reply. Seems they're killing off support entirely for GarageIO June 30th, 2024. I won't be updating the plug in.

> Hi,
> I do apologize for the multiple emails, I just received a more accurate update, please see below:
> 
> It is with regret that we must announce that support for your Garageio smart garage door controller will be ending on June 30, 2024. Cloud technology has advanced past what was cutting edge ten years ago and device connection support options are no longer feasible.
> 
> As a loyal Garageio user, there are two options being offered to continue to enjoy garage door control from your smartphone.
> 
> The second generation beam Smart Controller, model V2B, will be made available at a deeply discounted price of $59.00. A list of features of the V2B can be found on the [beamlabs.io](http://beamlabs.io/) website here at https://www.beamlabs.io/smart-controller. You will find features, security and support have been upgraded from the V1 Garageio controller. The V2B also meets the important UL325 safety standard for unattended garage door opener operation.
> 
> If your garage door opener is older, consider upgrading to a new beamUP garage door opener with the V3 Smart Controller. The V3 has the added advantage reading the state of your door directly from the opener’s logic board, making the door sensor or cable sensors things of the past. Click on the link to see opener features https://www.beamlabs.io/thunderbolt. As a loyal Garageio customer, openers with the V3 controller will be made available to you, factory direct, at a deeply-discounted prices.
> 
> Both V2B and V3B use the beam Home app. Please contact us directly at 1-888-323-9782 or [info@beamlabs.io](mailto:info@beamlabs.io) to order the V2B or beamUP smart garage door opener.
> 
> Best regards
> Beam Labs, LLC

**Comment by JedWare** [comment]
Well apparently someone decided to renew the certificate after all. The
upgrade path appears to only work with garageio with wireless sensors. I
have the wired multiple door garageio so not sure how long it will be
supported. They just have never sent a formal email either way as to
retiring the product.  It will at least work till next April.

[image: image.png]

**Comment by jonathanaitken** [comment]
I see garageio is doing and end of life on their hardware in June.
They are offering a discount on beam hardware.

What are your thoughts?  Will you buy beam or look at another option?




Thanks,

Jonathan

**Comment by JedWare** [comment]
Yes. I already switched out for a Meross  MSG200HK. It was only $69 and it
integrated seamless with existing door sensors.
